package Tests;

import org.junit.Assert;
import org.junit.Test;
import org.openqa.selenium.Cookie;
import utilities.TestBase;

import java.util.Set;

public class Day09_Cookies extends TestBase {


    /*  Cookies are temporary data/files that is generated by the browsers.
    It's a way for a website to remember you, your preferences, and your habits online.
    Cookies are stored in our computers as we visit the websites   */


    /*
    Class: Day09_Cookies
    Method: handleCookies
    -Go to amazon and automate the tasks:
    1. Find the total number of cookies
    2. Print all the cookies
    3. Get the cookies by their name
    4. Add new cookie
    5. Delete cookie by name
    6. Delete all of the cookies

     */


    @Test
    public void test() throws InterruptedException {

        //Go to amazon and automate the tasks:
        driver.get("https://www.amazon.com/");

        //. Find the total number of cookies
        Set<Cookie> allCookies = driver.manage().getCookies();
        int numberOfCookies = allCookies.size();
        System.out.println("Number Of Cookies : " + numberOfCookies);


        //2. Print all the cookies

        for (Cookie each : allCookies) {

            System.out.println("Cookie ==> " + each);
            System.out.println("Cookie Value :" + each.getValue());
            System.out.println("Cookie Name :" + each.getName());
        }


        //3- Get the cookies by their name
        System.out.println("Cookie Named : " + driver.manage().getCookieNamed("i18n-prefs"));  //entering cookie name and getting the entire cookie


        //4. Add new cookie
        Cookie cookie = new Cookie("my-fav-cookie", "apple-pie");
        driver.manage().addCookie(cookie);
        Thread.sleep(2000);

        Set<Cookie> newCookies = driver.manage().getCookies();
        System.out.println("New Number Of Cookie : " + newCookies.size());  //1 more than original number of cookie


        //5. Delete cookie by name
        driver.manage().deleteCookieNamed("session-id");
        Thread.sleep(2000);
        int lastNumberOfCookies = driver.manage().getCookies().size();
        System.out.println("Last Number Of Cookies : " + lastNumberOfCookies);


        //6-Delete all of the cookies and verify it
        driver.manage().deleteAllCookies();
        Thread.sleep(2000);
        int finalOfNumberOfCookies = driver.manage().getCookies().size();
        System.out.println("Final Of Number Of Cookies : " + finalOfNumberOfCookies);
        allCookies = driver.manage().getCookies();
        Assert.assertTrue(allCookies.isEmpty());
    }
}
